declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string
      CLERK_SECRET_KEY: string
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: string
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: string
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string
      NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string
      NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: string
      NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: string
      NEXT_PUBLIC_POCKETBASE_URL: string
      WEBHOOK_SECRET: string
      NEXT_PUBLIC_CRYPTO_PASSPHRASE: string
    }
  }
}

export {}
